// <auto-generated />
using Entekhab.Infrastructure.EfPersistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entekhab.Infrastructure.EfPersistance.Migrations
{
    [DbContext(typeof(EntekhabDbContext))]
    [Migration("20230924163227_add-junction")]
    partial class addjunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entekhab.Domain.Mojavez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Mojavez");
                });

            modelBuilder.Entity("Entekhab.Domain.Resid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Resid");
                });

            modelBuilder.Entity("MojavezResid", b =>
                {
                    b.Property<int>("MojavezesId")
                        .HasColumnType("int");

                    b.Property<int>("ResidsId")
                        .HasColumnType("int");

                    b.HasKey("MojavezesId", "ResidsId");

                    b.HasIndex("ResidsId");

                    b.ToTable((string)null);

                    b.ToView("ResidMojavez", (string)null);
                });

            modelBuilder.Entity("MojavezResid", b =>
                {
                    b.HasOne("Entekhab.Domain.Mojavez", null)
                        .WithMany()
                        .HasForeignKey("MojavezesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entekhab.Domain.Resid", null)
                        .WithMany()
                        .HasForeignKey("ResidsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
