// <auto-generated />
using Entekhab.Infrastructure.EfPersistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entekhab.Infrastructure.EfPersistance.Migrations
{
    [DbContext(typeof(EntekhabDbContext))]
    [Migration("20230924170131_add-junction-1")]
    partial class addjunction1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entekhab.Domain.Mojavez", b =>
                {
                    b.Property<int>("MojavezId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MojavezId"));

                    b.HasKey("MojavezId");

                    b.ToTable("Mojavez");
                });

            modelBuilder.Entity("Entekhab.Domain.Resid", b =>
                {
                    b.Property<int>("ResidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidId"));

                    b.HasKey("ResidId");

                    b.ToTable("Resid");
                });

            modelBuilder.Entity("MojavezResid", b =>
                {
                    b.Property<int>("MojavezesMojavezId")
                        .HasColumnType("int");

                    b.Property<int>("ResidsResidId")
                        .HasColumnType("int");

                    b.HasKey("MojavezesMojavezId", "ResidsResidId");

                    b.HasIndex("ResidsResidId");

                    b.ToTable((string)null);

                    b.ToView("ResidMojavez", (string)null);
                });

            modelBuilder.Entity("MojavezResid", b =>
                {
                    b.HasOne("Entekhab.Domain.Mojavez", null)
                        .WithMany()
                        .HasForeignKey("MojavezesMojavezId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entekhab.Domain.Resid", null)
                        .WithMany()
                        .HasForeignKey("ResidsResidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
